### ISSUE TITLE
Help with getting seeing-is-believing to run

### ISSUE THREAD

**Issue by sobopla** [brandoncc/vscode-seeing-is-believing#1]
Hi, I'm a code newbie so please forgive my lack of lexicon knowledge. 
I tried to run this with Sublime and it just made me hate Sublime and it's complexities more. 
Now I have it installed in VSC . 
What do you mean by 'If you want to see what a line returns, this is how you mark it to be annotated.

Seeing is Believing: Run'

Is "Seeing is Believing: Run" to be typed in the terminal?

**Comment by brandoncc** [comment]
That is a Visual Studio Code command. You can run it by clicking on "View", then "Command Palette..." in Visual Studio Code. You can then start typing the command you want to run in the palette and it will narrow down the results as you type. When you see the command you want, you can click on it or highlight it using the down arrow and hit enter.

VSC will also show a shortcut command on the "View" menu (to the right of "Command Palette...") which shows you how to access the command palette quickly, without needing to use the menus.

**Comment by sobopla** [comment]
Hi , when there is a require_relative 'file' , Seeing_is_believing gives an error and can't get past that line, even though the code runs fine without seeing_is_believing. 
Please advise, 
Thank you!

**Comment by brandoncc** [comment]
I just published an update to the extension which allows `require_relative` to work properly. Thanks for pointing out this issue. The same issue actually exists in similar plugins for other editors, but I changed the way the text is processed (by saving it to a temporary file and passing that to seeing-is-believing), which fixes the problem.

**Comment by sobopla** [comment]
Thanks for that, now I get an error when using SIB in rspec files:
describe SomeClass do # ~> NoMethodError: undefined method `describe' for main:Object
# ~> NoMethodError:

**Comment by brandoncc** [comment]
Make sure you have `require 'rspec'` and try changing `describe` to `RSpec.describe` (make sure BOTH "r" and "s" are capitalized). For the record, I don't think that the creator of seeing-is-believing intended it to be used with spec/test files. You should use an interactive tool like pry for that.

**Comment by sobopla** [comment]
So when my computer shut down I had to reinstall seeing_is_believing. Is there a way to make it stick?

**Comment by brandoncc** [comment]
That sounds like you were using a different ruby version and needed to install the gem in that ruby version. 

The execution looks like it is working, but you have an error appearing as well. I don't know what is causing that, as it is something specific to your machine.

As for the extension command not showing in the command pallette, there is no explanation for that. I would double check that you didn't accidentally uninstall the extension and then look again. 

Good luck!

**Comment by brandoncc** [comment]
I'm sorry to inform you that I am removing the update I made which allowed `require_relative` to be present in files run through this extension. I have found that it causes issues in some situations when write permissions are not present on directories. I would recommend using pry or a similar tool on projects which are large enough to to use requires.

**Comment by brandoncc** [comment]
You will be happy to know that @JoshCheek updated the `seeing_is_believing` binary to add the pieces needed to support this. If you update the gem and this extension `require_relative` should work for you now.
