### ISSUE TITLE
SiB not working after updating Ubuntu WSL packages

### ISSUE THREAD

**Issue by bubbavox** [brandoncc/vscode-seeing-is-believing#11]
When i use the SiB commands _run_ or _clean_, I'm getting the VS Code error `Command 'seeing_is_believing' does not exist. Is it installed?`, and all text in the file is erased.  The _mark_ command still works.  And SiB seems to be working properly in the shell.  

Steps: I installed Ubuntu, followed by the routine `sudo apt upgrade`.  Then I installed build-essential, ruby 2.7.4 (with ruby-install and chruby), SiB gem, gem updates, and finally VSCode + a few extensions.

I tested this with another computer, on which SiB was still working. Sure enough, after I ran `sudo apt upgrade` on that machine, it created the same SiB failure.  And now after a fresh install of Ubuntu, not upgrading pkgs and installing only _make_, I'm still getting the same error.

Edit: This is what I see in VSC's Window log when I try to run the SiB _run_ command:
```
[renderer1] [error] [Extension Host] Error: Unexpected SIGPIPE
	at process.<anonymous> (/home/bubba/.vscode-server/bin/f4af3cbf5a99787542e2a30fe1fd37cd644cc31f/out/bootstrap.js:1:370)
	at process.emit (events.js:315:20)
```

And in the extension's Runtime Status I see an uncaught error `write EPIPE`

**Comment by brandoncc** [comment]
Unfortunately, I don't use either VS Code (anymore) or Ubuntu. Sorry I can't help 😦  If you are able to identify the cause of the issue, I'd be happy to take a stab at fixing it or accepting a PR for the fix. I'm just not able to debug the issue on my machine.

**Comment by bubbavox** [comment]
The problem seems to be resolved with yesterday's VS Code update.  The previous update, 1.62.1, seems to have created issues with WSL.  I should have searched the VSCode issues page before posting here.  Thanks for the response though, and for your work on this extension.

**Comment by brandoncc** [comment]
I'm happy to hear this because I was thinking about it overnight and I couldn't figure out where to start to help you!

**Comment by bubbavox** [comment]
I was quite relieved, as SiB has become such a core part of my workflow! Curious... what is your preferred editor these days?

**Comment by brandoncc** [comment]
I'm using neovim and I'm quite happy with it. I have used vim bindings in every editor for years, which makes every other editor feel like a poor representation of vim....so I always end up back on it.

**Comment by bubbavox** [comment]
I want to give vim a try at some point.  I use a custom function layer to jump around text (arrow keys, home, end, delete, etc).  This is achieved with the windows app TouchCursor.

**Comment by brandoncc** [comment]
Here is my opinion... Use the editor that makes _you_ most happy and efficient. That will be different for everyone, and there is nothing wrong with that. If you have a good workflow, you are doing better than a lot of people who haven't figured out an optimal setup for them.
