### ISSUE TITLE
New flag you might be interested in: `--local-cwd`

### ISSUE THREAD

**Issue by JoshCheek** [brandoncc/vscode-seeing-is-believing#3]
Hi, I just released a new version of SiB, it allows the flag `--local-cwd` to be set, which will tell SiB to cd to the directory of the file before running it. Its primary advantage is that stack traces get a lot nicer, b/c SiB's temp directory is long. There's also a flag `--ignore-unknown-flags`, which can be used to provide the flag, taking advantage of the feature if it exists, while also being backwards compatible if it doesn't. Thought you might be interested :) [here](https://github.com/JoshCheek/atom-seeing-is-believing/commit/d98f7b4252a769b98cc2a4258a84d2be905d8b0a) is how I added it to the Atom editor.

<img width="914" alt="screen shot 2017-11-18 at 6 31 42 pm" src="https://user-images.githubusercontent.com/77495/32986088-d4ae5934-cc8e-11e7-8c92-fc3f81c8fe91.png">

**Comment by JoshCheek** [comment]
Oh, side thought: IDK how good vscode is, but it looks like it's got some cool annotation features built into it, so you might be interested in using them for more sophisticated integration (then again, that does add complexity). 

Eg you can get the results in JSON format and then add them in an overlay or something (looks like they do this with JavaScript documentation).

<img width="663" alt="screen shot 2017-11-18 at 6 34 00 pm" src="https://user-images.githubusercontent.com/77495/32986095-1c055c6a-cc8f-11e7-8cee-259ab057cd5c.png">

There's also a streaming option, which would allow you to display results as they become available, though it'd probably take a bit of work to figure out how to display them (I never got around to using it in an integration, but I was planning to either overlay them on the source line as they became available, or to open a second buffer, lock its scrolling to the main buffer, and then populate it as output was encountered).

![sib-streaming](https://user-images.githubusercontent.com/77495/32985943-045b62f6-cc8c-11e7-9e52-67c539b2663e.gif)

**Comment by brandoncc** [comment]
Thanks for letting me know about this @JoshCheek. I think this new flag should allow scripts to use `require` and `require_relative` 👍

**Comment by brandoncc** [comment]
I finally got around to adding this. I had some trouble at first, but then I looked at your Atom extension and figured out that I wasn't using the `--as` flag like you were. After I added that in the same way you did, it worked great. Thanks again for the heads up!
