### ISSUE TITLE
Error message in VSCode

### ISSUE THREAD

**Issue by 98-f355-f1** [brandoncc/vscode-seeing-is-believing#4]
I have been enjoying your extension for Visual Studio Code for the past year.  However, I just encountered a problem, maybe you can let me know how to fix this, or whats going on.

I have never had a single problem until today.  I opened up the VSCode and I started getting these error msgs, see attached picture.

I used it earlier today, shutdown and restarted the computer and now get this message when I use the f1 command and try to use the run.

However, if I use the seeing... filename.rb command from the shell... it still works.

Any idea to fix this?

Thank you,
Tom

![capture](https://user-images.githubusercontent.com/28711409/36497483-b23257f2-16f8-11e8-96f1-fed2db99612b.PNG)

**Comment by 98-f355-f1** [comment]
a new screen capture... VSCode changed the look of the error msgs, but msg content is still the same, but appears to have more detail.

![capture](https://user-images.githubusercontent.com/28711409/36497712-561b7bb4-16f9-11e8-8f9c-cedb79ab500d.PNG)

**Comment by brandoncc** [comment]
Oops, I know what the problem is. I'll deploy a fix. Sorry about that!

**Comment by brandoncc** [comment]
The problem should be resolved. Please let me know if the problem continues. By the way, v0.0.5 brought the ability to use `require_relative` with it, which is what caused this problem indirectly. You may enjoy being able to use that feature of seeing_is_believing 3.4.0+ 👍
